### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by karlbum** [DesktopECHO/Pi-Hole-for-WSL1#24]
when trying to install, it fails during the Debian installation with the following message

> This will take a few minutes to complete...
Installing LXrunOffline.exe and Debian -> Compacting install E: Unable to locate package libidn11
E: Unable to locate package libjson-c3
-> Install dependencies
E: Unable to correct problems, you have held broken packages.
/bin/bash: line 1: wget: command not found
/bin/bash: line 1: wget: command not found
dpkg: error: cannot access archive './cloudflared-stable-linux-amd64.deb': No such file or directory
chmod: cannot access 'cloudflared': No such file or directory
mv: cannot stat 'cloudflared': No such file or directory
update-rc.d: error: unable to read /etc/init.d/cloudflared
/bin/bash: line 1: gpg: command not found

according to the log seems it was stuck at perl

[Pi-hole Dependency Stage.log](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/files/7002474/Pi-hole.Dependency.Stage.log)

**Comment by DesktopECHO** [comment]
Thank you for the bug report.  

I just commited a fix so the installer downloads the correct Debian image.  This is because Debain version 11 was released recently and to-date have only qualified the Pi-hole installer to work on version 10.

Please run the uninstaller script (as administrator) left by the falied install attempt.  Default location is **C:\Program Files\Pi-hole\Pi-hole Uninstall.cmd** 

When uninstall is complete, download the lastest version of [PH4WSL1.CMD](https://raw.githubusercontent.com/DesktopECHO/Pi-Hole-for-WSL1/master/PH4WSL1.cmd) and retry the install.  

You shoud be good to go -- Let me know if you have any furthre issues.

Thanks,
D.
