### ISSUE TITLE
Not an Issue - question

### ISSUE THREAD

**Issue by pumpkinpieman** [DesktopECHO/Pi-Hole-for-WSL1#5]
Will you implement the task to be scheduled automatically after installation? Is this something I can help test? :D

**Comment by DesktopECHO** [comment]
Hi I don't understand your question.  Do you want Pi-hole to start up when your system boots?

**Comment by pumpkinpieman** [comment]
Correct.

**Comment by DesktopECHO** [comment]
Right now it's just a matter of clicking a couple of checkboxes and entering in your password on the scheduled task to have it start at boot time.  

Did the Pi-hole installer create a scheduled task for you?  If it didn't, its a bug I've since resolved.

You can re-install Pi-hole or to re-create just the scheduled task, the following command should do the trick (replace C:\Program Files with your chosen folder)

`SCHTASKS /CREATE /RU "%USERNAME%" /RL HIGHEST /SC ONSTART /TN "Pi-hole for Windows" /TR '"C:\Program Files\Pi-hole\Pi-hole_Task.cmd"' /F`

**Comment by azamet90** [comment]
> 
> 
> Right now it's just a matter of clicking a couple of checkboxes and entering in your password on the scheduled task to have it start at boot time.
> 
> Did the Pi-hole installer create a scheduled task for you? If it didn't, its a bug I've since resolved.
> 
> You can re-install Pi-hole or to re-create just the scheduled task, the following command should do the trick (replace C:\Program Files with your chosen folder)
> 
> `SCHTASKS /CREATE /RU "%USERNAME%" /RL HIGHEST /SC ONSTART /TN "Pi-hole for Windows" /TR '"C:\Program Files\Pi-hole\Pi-hole_Task.cmd"' /F`
i get this error on giving that command: ERROR: There was nothing between user accounts and security IDs.

**Comment by DesktopECHO** [comment]
Try this instead:

`````SCHTASKS /CREATE /RL HIGHEST /SC ONSTART /TN "Pi-hole for Windows" /TR '"C:\Program Files\Pi-hole\Pi-hole_Task.cmd"' /F`````

Does it create the scheduled task?  If so, open Task Scheduler and try to run it and see if it works.
