### ISSUE TITLE
Not working fully

### ISSUE THREAD

**Issue by Klektic** [DesktopECHO/Pi-Hole-for-WSL1#72]
I've setup and followed the instructions as per the reddit thread. My network is setup as static and dns is 127.0.0.1 Some things get blocked but it is not very much. This [test site](https://d3ward.github.io/toolz/adblock.html) only reports 10% block

The debug log says I need to run in admin mode for dhcp but dhcp has been disabled.(wish I had read that before spending a quarter of a day trying to get bridge mode to work) [Here is log](https://tricorder.pi-hole.net/AKboKnOV/) So im not sure if it has anything to do with the issue.

Much thanks.

**Comment by jfb-pihole** [comment]
The devs here don't have access to your debug log, and your log expires in 48 hours.

**Comment by DesktopECHO** [comment]
[Reddit Thread](https://www.reddit.com/r/pihole/comments/ya9nqs/comment/itans5z/)

First:  Apologize to the devs in the thread above for being an insufferable jerk.
Second:  Fix the extremely incorrect edits to your Reddit OP, which has degenerated into useless shitpost spam.

If you do as asked, I may be inclined to offer some technical guidance.  

Otherwise, please run `Pi-hole Uninstall.cmd` go away, and don't come back until you've learned some manners.
