### ISSUE TITLE
Not fully working #2

### ISSUE THREAD

**Issue by Klektic** [DesktopECHO/Pi-Hole-for-WSL1#73]
Sorry was not aware that debug logs need to be authorized my bad.

I have not commented in any other thread on this website.

My edit is accurate. A shitpost would be purposely posted to distract or anger people that was not my intention. I give respect as it is given. If the support had said simply there is nothing in the log to indicate whats wrong. We cannot support you given that software was not released by us. That would have been the end of it; plenty of my time has been wasted as well. Instead all that was posted was an url with no indication of what he/she meant for me to do.

But I get that no one wants to be logical because I was mildly rude

**Comment by jfb-pihole** [comment]
"We cannot support you given that software was not released by us."

I only wrote this at least 5 times.

"My edit is accurate. "

Your edit removed any possibility that anybody could help you, because you completely removed the problem statement.  This is solely self-inflicted pain.

"f the support had said simply there is nothing in the log to indicate whats wrong"

I specifally explained to you that the debug log was limited by the underlying OS and did not provide anything we could use to help you.

"plenty of my time has been wasted as well."

More self-inflicted pain.

" give respect as it is given:

Nobody showed you any lack of respect.  We did (accurately) tell you where to get the support you sought, and explained why to go to that source (which is this forum where we are currently posting).

"all that was posted was an url with no indication of what he/she meant for me to do."

You asked a follow-up question on that topic, which was quickly answered.

**Comment by Klektic** [comment]
You are deliberately altering the timeline of events to make yourself feel/look better.

The first comment you asked was whether or not Im running in vm or docker. I answer and you immediately just post the url with no explanation. You do not say anything else. Requiring me to read your mind on what you meant. That is rude, that is how you started this whole thing, that is why I responded in kind. I came asking for help and was immediately shown the door, that is rude.

There was never any help to be gained from that forum you made that CLEAR in you very first interaction.

**Comment by jfb-pihole** [comment]
Feel free to read the entire Reddit post again.  It's untouched and all the replies and comments are as posted.

After burning any bridges over on Reddit (because you removed your problem statement), here you are on your last resort for WSL1 and you've already pissed off the dev here in no time.

I think this is a "you" problem.

Best wishes resolving your problem.

**Comment by Klektic** [comment]
I have no idea what the dev is talking about another thread on this site, this account is brand new. The reason he's pissed off is because you went out of your way to to now actively block help by contacting him. Can't be bothered to help on reddit but can be bothered to block it on another site. That reflects poorly on you. 

Last resort please. I can get plenty of ad blocking already. I just wanted to use this for a network wide blocking. There are plenty of alternatives. Not to mention the internet is anonymous.

yes the thread is still there. You can see your posts as well in order. I have not deleted it.

Once again a passive-aggressive sign off comment is very childish.

**Comment by DesktopECHO** [comment]
> The reason he's pissed off is because you went out of your way to to now actively block help by contacting him

They did nothig of the sort; you have gone completly off the rails.  Please go away.
